### ISSUE TITLE
Asking about the code

### ISSUE THREAD

**Issue by didaquis** [AnthonyLevillon/RiskyPicker#1]
Hi @AnthonyLevillon ! 👋🏻

I found your Slack App and it's fantastic.

Would you be so kind as to upload the rest of the source code?

**Comment by AnthonyLevillon** [comment]
Hi @didaquis,

I wanted to rewrite RiskyPicker with NodeJS as it was written in PHP before but I'm not using slack anymore and don't really have time to maintain it.

Sorry about that. I'll ping you a message if things changes in the next months.

Cheers,
Anthony
